name: Splatoon Notification

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # ← v3からv4に新しくしました
      - name: Set up Python
        uses: actions/setup-python@v5 # ← v4からv5に新しくしました
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        # ↓↓↓ ここが一番重要です！ ↓↓↓
        run: python splatoon-checker/notify.py
